services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./src/Dockerfile
    command: npm run start:dev
    env_file:
      - ./.env
    networks:
      - mongo-net
      - redis_net
    ports:
      - "3333:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo:5.0
    ports:
      - "27017:27017"
    networks:
      - mongo-net
    volumes:
      - './data:/data/db'
  redis:
     container_name: redis
     image: redis
     restart: always
     ports:
      - '6379:6379'
     networks:
      - redis_net
        #volumes:
        #- 'cache:/data'
networks:
  mongo-net:
  redis_net:
