###
GET http://localhost:3000/user


###
GET http://localhost:3000/user/63f11c9b0a21703294493137
Content-Type: application/json


###
DELETE http://localhost:3000/user/63f1293e0a2170329449313b
Content-Type: application/json

{

}


###
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "userName": "mohamadhasanT",
    "email": "tbz.mohamadhasanT@yahoo.com",
    "mobileNumber": "+989142371301",
    "password": "95440012WEek",
    "avatar": "avatar.png",
    "level": "upper-Intermediate"
}


###
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email": "tbz.mohamadhasan@yahoo.com",
    "password": "95440012WEek"
}

###
POST http://localhost:3000/auth/signout
Content-Type: application/json

{

}


###
GET http://localhost:3000/auth/me
